sudo: false
language: java
jdk:
- oraclejdk8
script:
- test/run.sh
notifications:
  slack:
    secure: LkyFJGV9lUWqkoQcRtKHXrdhZ4+jVnGHtJLqGRB5KTzyE65K7yfMEBjXnw7amzK/KyaUjQIGAtfF7qjWZ8+WKRfuY48me5T8ivvvppKUkAkxIJiLNIQGVCMVyg1/lG2DXapjaCfa3/PmqVAjbcnxeAnatDDBgSeRXQpzkpKA0ys=
